// Generated by CoffeeScript 1.6.3
/*
@name jquery-bulb
@description Slice/split DOM. Decouple element from stream. Use at your own risk!
@version 0.0.1
@author Se7enSky studio <info@se7ensky.com>
*/


/*! jquery-bulb 0.0.1 http://github.com/Se7enSky/jquery-bulb*/


(function() {
  var plugin;

  plugin = function($) {
    "use strict";
    var bulb;
    bulb = function($el) {
      var $parent, $parentClone;
      $parent = $el.parent();
      $parentClone = $parent.clone().empty();
      $el.nextAll().appendTo($parentClone);
      $parentClone.insertAfter($parent);
      $el.insertAfter($parent);
      if ($parent.children().length === 0) {
        return $parent.remove();
      }
    };
    return $.fn.bulb = function(selector, parent) {
      if (parent == null) {
        parent = true;
      }
      this.each(function() {
        if ((selector != null) && $(this).closest(selector).length !== 0) {
          while (!$(this).parent().is(selector)) {
            bulb($(this));
          }
        }
        if (parent) {
          return bulb($(this));
        }
      });
      return this;
    };
  };

  if (typeof define === 'function' && define.amd) {
    define(['jquery'], plugin);
  } else {
    plugin(jQuery);
  }

}).call(this);
